### ISSUE TITLE
CouchPotato cannot add without IMDB identifier

### ISSUE THREAD

**Issue by kurnalbert** [ngovil21/PlexRequestChannel.bundle#13]
I have PlexRequest installed and have Sonarr and CouchPotato connected. Sonar works without any issue and can add shows when requested.

With CouchPotato, I can only receive search results when using TheMovieDatabase (using OpenMovieDatabse just provides a message that the app is not responding). When adding a movie request, it gets added to PlexRequest fine but fails to add to CouchPotato. CouchPotato will pop up an error in the lower corner stating that a movie cannot be added to CouchPotato without an IMDB identifier. 

Could you possibly point me in the right direction to try to troubleshoot the issue?

Thanks!

**Comment by ngovil21** [comment]
Hmmm, I fixed the bug with TheMovieDatabase sending to CouchPotato. I'm not aware of any problems with the OpenMovieDatabase. Please try the latest release and let me know if you still have problems.

**Comment by albertvolkman** [comment]
This is failing on the development branch for me.

**Comment by ngovil21** [comment]
Would you be able to post your log when it fails? It's working for me.

**Comment by kurnalbert** [comment]
TheMovieDatabase is now working for me on the development branch. Thanks a million!

**Comment by albertvolkman** [comment]
Nevermind, I just needed to restart PMS. Works!

**Comment by ngovil21** [comment]
Glad to hear that. Closing this issue.
