### ISSUE TITLE
Could not send show to Sonarr!

### ISSUE THREAD

**Issue by seanap** [ngovil21/PlexRequestChannel.bundle#15]
[com.plexapp.plugins.plexrequestschannel.txt](https://github.com/ngovil21/PlexRequestChannel.bundle/files/145743/com.plexapp.plugins.plexrequestschannel.txt)

Hi, I'm getting the error message "Could not send show to Sonarr!".  Couchpotato is working great, but it looks like it's having a hard time connecting to Sonarr.   In my settings the url is http://127.0.0.1:8989 , I've double and tripple checked the API key and I checked the box for auto add.  When I View the Request and click the show and then select Send to Sonarr the logs say the following:
`2016-02-24 19:35:04,446 (cf8) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 1377 bytes
2016-02-24 19:35:04,493 (22a0) :  DEBUG (runtime:717) - Handling request GET /video/plexrequestchannel/sendtosonarr?locked=unlocked&id=278200
2016-02-24 19:35:04,493 (22a0) :  DEBUG (runtime:814) - Found route matching /video/plexrequestchannel/sendtosonarr
2016-02-24 19:35:04,494 (22a0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:8989/api/Series/Lookup?term=tvdbid:278200'
2016-02-24 19:35:04,756 (22a0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:8989/api/Profile'
2016-02-24 19:35:04,763 (22a0) :  DEBUG (logkit:13) - Profile id: 6
2016-02-24 19:35:04,763 (22a0) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:8989/api/Series'
2016-02-24 19:35:04,845 (22a0) :  ERROR (networking:217) - Error opening URL 'http://127.0.0.1:8989/api/Series'
2016-02-24 19:35:04,846 (22a0) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 1459 bytes`

**Comment by ngovil21** [comment]
There was an error, but I'm not sure it's the same as the issue you are having. Please update the channel and try again. I added some more logging, which will give more information.

**Comment by seanap** [comment]
I love the improvements you've made!

 I've updated to the latest, restarted the computer, and tried to manually send a TV show request to Sonarr and it still fails.  I've tried a few different URL's: localhost:8989, 127.0.0.1:8989,  192.168.x.x:8989, and none seem to work.  I've attached the logs but it's still showing the same networking error opening URL /api/series
[com.plexapp.plugins.plexrequestschannel.txt](https://github.com/ngovil21/PlexRequestChannel.bundle/files/147354/com.plexapp.plugins.plexrequestschannel.txt)

**Comment by ngovil21** [comment]
Alright just use 127.0.0.1 for now. I added a traceback that will hopefully give more information.

Please update the channel again. To enable more debugging, go to Manage Channel and select "Turn on debugging" (if it says turn **off** then leave it alone).

Then try sending a show to Sonarr and let me know what you get in the log.

Thank you for the donation!

**Comment by seanap** [comment]
[com.plexapp.plugins.plexrequestschannel.txt](https://github.com/ngovil21/PlexRequestChannel.bundle/files/147434/com.plexapp.plugins.plexrequestschannel.txt)

Same error, "Could not add show" Logs attached.

Maybe it's SSL related? I'm going to enable SSL on Sonarr and see what happens

**Comment by ngovil21** [comment]
No it probably isn't SSL related if you don't have SSL enabled on Sonarr already. Could you attach a pic of what your options for Sonarr in the channel preferences look like?

**Comment by seanap** [comment]
![image](https://cloud.githubusercontent.com/assets/17012946/13338097/36999486-dbed-11e5-95e7-32b5b357386b.png)
![image](https://cloud.githubusercontent.com/assets/17012946/13338125/5fa5f5c2-dbed-11e5-8a05-3c6d4b21030f.png)

**Comment by seanap** [comment]
In the Plex Channel, if I go to "Manage Sonarr" it returns an error "This channel is not responding."

**Comment by ngovil21** [comment]
Alright I think I know what the problem is. Python can have problems with Windows paths. Do you mind switching to the `development` branch and trying to add a send a show to sonarr with your current settings. And then can you try with the Root folder path as `T://TV` or with it empty. (Empty should get the default value from Sonarr)

You can do these in one go and then send me the log afterwards. Thanks for your patience.

**Comment by seanap** [comment]
Success!

I switched to the developer branch, tried it with the same settings and no luck, then tried it with `T://TV` and still no luck, when I just deleted the path in the Root Folder field it successfully added the show to Sonarr.
[com.plexapp.plugins.plexrequestschannel.txt](https://github.com/ngovil21/PlexRequestChannel.bundle/files/147489/com.plexapp.plugins.plexrequestschannel.txt)

Was there something I missed when installing Py?

**Comment by ngovil21** [comment]
No you can see my edits in the previous post, but I think you were using the wrong slash. On windows you should use `\`.

The Root Folder is optional though, so no need to really use it, unless you want things to go somewhere other than the default location.

**Comment by seanap** [comment]
Doh! I should have known better. Thank you so much for your help!
