### ISSUE TITLE
[Feature Request] List existing requests

### ISSUE THREAD

**Issue by pmow** [ngovil21/PlexRequestChannel.bundle#18]
It would be great if we could see existing requests not entered through the channel.

**Comment by ngovil21** [comment]
From which source? This channel isn't affiliated with [PlexRequests](http://plexrequests.8bits.ca/). I don't know if there is an API for that.

**Comment by pmow** [comment]
Couchpotato is the big one for me because there is zero activity for Sonarr.  I know you can delete them so I assumed you could just list them:
[https://couchpota.to/forum/viewtopic.php?t=2235](url)

Yes, I'm familiar with PlexRequests but I think this channel is more elegant.  Neither project currently lists what the server is already looking for.  When getting a list of movies, it would be helpful to list all movies CouchPotato is looking for (via automation for example), instead of just the ones added via the channel.

**Comment by ngovil21** [comment]
I could create a menu that lists the movies in Couchpotato similar to what I have done for Sonarr/Sickbeard. I prefer to keep the listings separate.

**Comment by pmow** [comment]
What about an checkbox option to use the SB/Sonarr/CP lists?  After all, everything in the bundle should be in the web app.  This way users can see everything server is looking for, not only what was requested through the channel.

Having an option like "Manage Couchpotato" is better than nothing, but many barely know about Plex let alone the management apps on the backend.

**Comment by ngovil21** [comment]
Well it's more than that. Sonarr/Sickbeard shows are on a continuous basis and there will be lots of shows.

I am adding a menu that will show all shows that are in Couchpotato. You will be able to allow other users to view this menu through the `Manage Channel` -> `Manage User` -> `Allow Manage Automation` on an individual user basis.

In the Manage Couchpotato menu, you will be able to see the movies being searched for in Couchpotato and delete movies from it. Any user that has access to the menu will have this ability.

**Comment by ngovil21** [comment]
So I have pushed the feature to the master branch now. You can now view Couchpotato monitored movies through the main menu and delete movies from there. If you would like to allow individual users to access the menu you can do so under Manage Channel -> Manage Users.

I understand you wanting to show the couchpotato requests in the requests menu, but it will get cluttered if all the content is visible there (movies and tv shows, and in the future music). I prefer to keep the souces separate from a development standpoint as well.

**Comment by pmow** [comment]
Thanks.  Enabling a user gets me "user can now manage Sonarr".  I'm guessing this is both Sonarr and CP.

I personally don't want users to have read/write but maybe someone else would use this management interface.
