### ISSUE TITLE
Add localized Movietitles and Description

### ISSUE THREAD

**Issue by j4m** [ngovil21/PlexRequestChannel.bundle#19]
Please add an option to choose the language of Movietitles and Descriptions

For example TVDB and TMDB URL have to contain  `&language=fr`

**Comment by ngovil21** [comment]
Good idea. I added in 39a5f2e0155f5bf5a04b21f9542152cdb3e34aee.

**Comment by j4m** [comment]
Thanks, it works perfectly!
