### ISSUE TITLE
All Users are Admins

### ISSUE THREAD

**Issue by j4m** [ngovil21/PlexRequestChannel.bundle#20]
All Plex Home Users are recognized as Admins

> DEBUG (Session:171) - User is Admin

**Comment by ngovil21** [comment]
Have you tried enabling the option to authenticate using plex.tv in the Preferences?

**Comment by j4m** [comment]
Oh, that works but the advice 

> (Use if you do not have Plex Home enabled)

is very confusing!? I have enabled Plex Home...

**Comment by ngovil21** [comment]
In your Plex Server settings do you have networks that are allowed without authentication?

**Comment by j4m** [comment]
Yes, i do have other networks enabled. I disabled them and it's working fine now.
Thanks.
