### ISSUE TITLE
Users can add/delete from feeder applications

### ISSUE THREAD

**Issue by cliffp** [ngovil21/PlexRequestChannel.bundle#24]
When a managed user (not administrator) accesses PlexRequest Channel, they can delete requested content directly from feeder applications (CP or Sonarr). This is by default permitted? Should be default deny.

**Comment by ngovil21** [comment]
Maybe the authentication isn't working. Try using authenticate using plex.tv in the channel settings.

**Comment by cliffp** [comment]
Also tried to use authentication via plex.tv, no change. Also, remote non-managed users "friends" can access CP and/or Sonarr queue management and delete said items.

**Comment by ngovil21** [comment]
Could you send me a PM on the Plex Forums with a log of a non-managed user accessing the channel? Create a test plex user that your PMS is shared and give it access to channels. Then enter the channel on that account and go to some of the menus.

**Comment by cliffp** [comment]
Of course. Will do once I return home.

**Comment by cliffp** [comment]
After creating a test user and giving it access to channels, I signed in with the test user account, and everything started working properly. the test unmanaged user could not manage couchpotato or sonarr queues, or manage requests. I'm satisfied, and apologies for any confusion! Great app.
