### ISSUE TITLE
[Feature Request] Pushbullet Channel Support

### ISSUE THREAD

**Issue by JustinGrote** [ngovil21/PlexRequestChannel.bundle#25]
Heyo,

This is a minor one, if you could add pushbullet channel support so I can specify a channel, I have a shared pushbullet channel that works as a feed for people to see when new stuff is requested. Plexrequests currently sends here and it'd be great for this channel to go here too.

Minor thing, i'm currently using IFTTT to manually sync for now. Cheers and thanks for a great solution!

**Comment by ngovil21** [comment]
Sorry I didn't check Github for a couple of days. I added the feature in the latest push.

**Comment by JustinGrote** [comment]
I will never complain about 2 days for a fix. Much obliged sir, thank you very much for a fantastic native solution!

**Comment by theCheek** [comment]
Just a note on this, the field name I think was wrongly named 'pushover channel' not pushbullet channel - may want to fix this to avoid confusion. Also, perhaps advise people not to put a # tag in front of the channel or it won't work. Thanks!
