### ISSUE TITLE
Return user who made request

### ISSUE THREAD

**Issue by ngovil21** [ngovil21/PlexRequestChannel.bundle#3]
Keep track of the user who made a request and show in notification.

**Comment by ngovil21** [comment]
Currently only the users local token can be used from the Plex API. No way to identify the user from the token however.

**Comment by ngovil21** [comment]
Going to have users register themselves everytime a new token is detected. Hopefully gives someway to identify users.

**Comment by pinkzeppelinx** [comment]
Perhaps tic boxes in a list of users that are allowed... Nothing is stopping them from choosing someone else, but they don't know that.

Can you have them sign in to myplex within the channel like the way plexrequests does it ?

**Comment by ngovil21** [comment]
I think the user entering in their name is good enough, tickboxes seems a lot. I will look into adding your own name for the user in the Manage User menu.

I could have the user login. There's no password input box in a plex channel, so their password will be visible while logging in.

**Comment by pinkzeppelinx** [comment]
I noticed I was able to do that with a 'user' account after I posted the comment.. sorry ;)

Since the request shows up in the PMS log  along with the IP can a grep be done to find username that way?

Either way asking for the username is great!

**Comment by ngovil21** [comment]
I don't really want to go grepping through the logs. Currently users are identified by their token and I don't want to have people logging the tokens in the log. It's a security issue.

I added the ability to manually edit usernames under Manage Channel -> Manage Users -> Rename User
