### ISSUE TITLE
Plex Media Player issues

### ISSUE THREAD

**Issue by dhighet** [ngovil21/PlexRequestChannel.bundle#35]
Works great in web/Android, though issues with the new PMP. No way to input requests, just a list of every possible character.
![plex media player 2016-07-07 19 37 15](https://cloud.githubusercontent.com/assets/15894936/16675910/5001faf8-447a-11e6-8587-51c55ad38915.png)

**Comment by ngovil21** [comment]
PMP does not properly implement a keyboard for channels. This is the alternative keyboard. You can click the characters to input the request.

**Comment by ngovil21** [comment]
#30
