### ISSUE TITLE
Users need to enter title by on screen keyboard

### ISSUE THREAD

**Issue by flixajki** [ngovil21/PlexRequestChannel.bundle#44]
Could you please change it so users can type it directly like owners can ?

**Comment by ngovil21** [comment]
The on screen keyboard is used in certain clients that do no support the default input menu. Users should be able to directly type in the Web Client, and on Android. Other clients do not have keyboard support.

Users can override this setting by choosing Switch to Device Keyboard. If a keyboard shows up please let me know which device they are using and I will update the channel. If no keyboard shows up, then they will have to use the alternative keyboard. This is a limitation of the Plex Client implementation and nothing I can do about it.

**Comment by ngovil21** [comment]
see issue #30
