### ISSUE TITLE
Sick rage support (enhancement)

### ISSUE THREAD

**Issue by trackermb** [ngovil21/PlexRequestChannel.bundle#9]
Hi there is there any possibility of sick rage support being added?

Thanks

**Comment by ngovil21** [comment]
Yes I have added it in already, but it is untested because I don't use sickrage myself. If you would like to test it for me that would be great! Otherwise I will probably do an installation this weekend and push out the new features to the master branch soon after that if all is well.

**Comment by ngovil21** [comment]
@trackermb This has been implemented in the master branch. Mind testing it out for me? I'm having some issues installing SickRage.

**Comment by ngovil21** [comment]
I got the Sickrage installation to work, but it seems really buggy. Not able to add shows from inside of the application and using the api has not worked at all, giving vague errors. There's no documentation on the api either, so this will be tough.

**Comment by joebetsill** [comment]
Do SickRage and Sickbeard share the same API? If so, I'll gladly test this out for you.

**Comment by ngovil21** [comment]
They share a similar api as in the same commands work, but when I was testing it out the SickRage api kept giving errors. I couldn't figure out what parameters it needed. Currently disabled it.

Do youstill use Sickbeard?

**Comment by joebetsill** [comment]
Yes. Well, I actually use a Sickbeard fork that handles torrents-- which is
exactly what Sickrage is, but my setup works flawlessly, so I don't want to
mess with it. :P

Sooner or later I'll switch to Sickrage.

**Comment by ngovil21** [comment]
@joebetsill ya I was targeting sickrage because most people use that. I've defaulted to sickbeard for now, so you can try that in the development branch and let me know if it works.

When I have sometime I'll inquire on the SickRage forums on getting the api to work.

**Comment by joebetsill** [comment]
I'll try it when I get home and let you know. Thanks!

**Comment by joebetsill** [comment]
On mobile, I don't have a "Yes" button when it asks if I want to request it-- just a "No".

![screenshot_20160209-133028](https://cloud.githubusercontent.com/assets/7346727/12927014/ec292bca-cf33-11e5-9075-796e5b1ae54c.png)

**Comment by ngovil21** [comment]
I could tell it was Android. Fixed it now in the development branch.

**Comment by joebetsill** [comment]
That did the trick! I'll let you know if I run into any issues. Thanks!

**Comment by ngovil21** [comment]
@trackermb I have tried to make the required changes for SickRage integration, but I can't get my installation of SickRage to work properly. Would you mind testing it out? Changes are in the development branch.

**Comment by jakeman2048** [comment]
It seems SickRage doesn't work properly with POST methods. I tested it with GET methods and it seems to work just fine. I used urllib.urlencode to get the existing variables converted but I'm not sure if that's ideal for plex plugins.

@ngovil21 Here's what I used to my install working: http://www.htpcguides.com/install-sickrage-ubuntu-vivid-vervet-15-x-and-later/

**Comment by ngovil21** [comment]
@jakeman2048 Yes that was the issue I saw with SickRage, I wasn't able to add shows. Do you think SickRage might expect a PUSH instead?

**Comment by jakeman2048** [comment]
@ngovil21 Here's what I changed to mine working. Basically, just import urllib, then change every sickbear_url call to use GET:
resp = JSON.ObjectFromURL(sickbeard_url + "api/" + Prefs['sickbeard_api'] + '?' + urllib.urlencode(data))

Was going to submit a pull request, but wasn't sure how you wanted to actually implement this, since it could break sickbeard.

**Comment by ngovil21** [comment]
Oh I get what you're saying now. So you are able to add shows using a GET request? That should be easy to fix. Basically the request would become:
`resp = JSON.ObjectFromURL(sickbeard_url + "api/" + Prefs['sickbeard_api'], data=data, method='GET')`

That should work in essence. I'll test it later with Sickbeard as well. Not hard thing to do different requests based on the fork either. Thanks for this.

**Comment by jakeman2048** [comment]
Awesome, that worked too and it seems better than having to import another module. haha

**Comment by guru69** [comment]
First off, great addon! Thanks for this.
Are you guys testing with github.com/SiCKRAGETV/SickRage or github.com/SiCKRAGE/SickRage ?
I am on github.com/SiCKRAGE/SickRage after several issues using the other one. I am getting "Error Retrieving SickRage Shows" when I click "Manage SickRage" on web and droid clients.

**Comment by ngovil21** [comment]
@jakeman2048 That mostly did the trick, Sickbeard wanted a 'POST', but that wasn't a difficult fix. I am able to manage SickRage through the channel, but I'm still unable to add shows. Not sure if my SickRage installation is still messed up, or if there's still a problem. Would you mind trying out the development branch for this?

@guru69 Almost there with SickRage support. If you would like to try it out, Manage SickRage should now work on the development branch, not sure if Adding Shows works. Try it out and let me know.

**Comment by jakeman2048** [comment]
@ngovil21 Development branch seems to work just fine!

**Comment by guru69** [comment]
Thanks ngovil21 you are right. Everything seems to work great in the development branch

**Comment by ngovil21** [comment]
Great it's now pushed to the master branch. Thanks for your help guys.
